############# THIS SCRIPT WAS GENERATED BY GEMINI #############

import torch
import os
import difflib
import pandas as pd
import numpy as np
from bonito import util
from bonito.reader import Reader, read_chunks
from nnsight import NNsight

##############################
######## MODEL SETUP #########
##############################

torch._dynamo.disable() 
import warnings
warnings.filterwarnings("ignore", category=UserWarning, module="torch.nn.attention.flex_attention")

model_path = "dna_r10.4.1_e8.2_400bps_sup@v5.2.0"
bonito_model = util.load_model(model_path, device="cuda" if torch.cuda.is_available() else "cpu")
model = NNsight(bonito_model._orig_mod)
model_dtype = next(model.parameters()).dtype # Gets the float16 type

##############################
######## FUNCTIONS ###########
##############################

def output_to_abs_in_idx(idx):
    return (idx * 6) - 14

def get_homopolymer_len(string, idx):
    ''' Get the number of repeating characters at the given idx '''
    if not string or idx < 0 or idx >= len(string):
        return 0, 0, 0
        
    begin = end = idx
    char = string[idx]
    length = 1

    while (begin > 0 and string[begin - 1] == char):
        length = length + 1
        begin = begin - 1
    
    while (end < len(string) - 1) and string[end + 1] == char:
        length = length + 1
        end = end + 1

    return (length, begin, end)

def is_single_isolated_deletion(str1, str2):
    """
    Checks if str2 is exactly str1 with ONE deletion, 
    and ensures that the deleted base has a homopolymer length of EXACTLY 1 in str1.
    """
    matcher = difflib.SequenceMatcher(None, str1, str2)
    opcodes = matcher.get_opcodes()
    
    # We expect exactly 3 opcodes for a single deletion: ['equal', 'delete', 'equal']
    if len([tag for tag, _, _, _, _ in opcodes if tag != 'equal']) != 1:
        return False, 0, ""
        
    for tag, i1, i2, j1, j2 in opcodes:
        if tag == 'delete':
            # 1. Check it's only one base deleted
            if (i2 - i1) != 1:
                return False, 0, ""
            
            # 2. Check the true length in the DECODED string (str1)
            str1_hlen, str1_hbegin, str1_hend = get_homopolymer_len(str1, i1)
            
            # 3. STRICT CHECK: Must be length 1 (an isolated base, not a homopolymer)
            if str1_hlen == 1:
                deleted_base = str1[i1]
                return True, i1, deleted_base
            else:
                return False, 0, ""
            
    return False, 0, ""

##############################
######## MAIN LOOP ###########
##############################

data_dir = "../data/reads/" # Update this
reader = Reader(data_dir)
reads = reader.get_reads(
    data_dir, 
    do_trim=True,
    scaling_strategy=model.config.get("scaling"),
    norm_params=model.config.get("standardisation")
)

NUM_READ = 1
for i in range(1, NUM_READ):
    next(reads)
first_read = next(reads)

records = []
alphabet = {1: "A", 2: "C", 3: "G", 4: "T"}

print(f"--- Generating Negative Controls for Read {NUM_READ} ---")

# 1. Grab the raw signal exactly like you do in Test_Inputs_new.py
raw_stndrd_signal = first_read.signal

chunksize = 4000
overlap = 400
step_size = chunksize - overlap

for chunk_idx, chunk_start in enumerate(range(0, len(raw_stndrd_signal) - chunksize + 1, step_size)):
    if chunk_idx >= 5: 
        break
        
    chunk_end = chunk_start + chunksize
    chunk = raw_stndrd_signal[chunk_start:chunk_end].copy()
    
    device = "cuda" if torch.cuda.is_available() else "cpu"
    # FIX 1: Use model_dtype instead of torch.float32
    clean_input = torch.tensor(chunk, dtype=model_dtype).view(1, 1, chunksize).to(device)
    
    with model.trace(clean_input):
        clean_output_proxy = model.output.save()
        
    clean_logits = clean_output_proxy.detach()
    clean_str = bonito_model.decode(clean_logits[:, 0, :])
    
    # Use the exact same Viterbi extraction from find_kmers.py
    viterbi_tensor = bonito_model._orig_mod.seqdist.viterbi(clean_logits.to(dtype=torch.float32))
    
    # Flatten it into a standard Python list
    viterbi_path = viterbi_tensor.flatten().tolist()
    
    # Append -1 to match your original find_kmers logic
    viterbi_path.append(-1)


    isolated_candidates = []
    last_state = -1
    slice_start = 0
    slice_length = 0
    
    for t in range(len(viterbi_path)):
        current_state = viterbi_path[t]
        if current_state == 0: 
            continue
            
        if current_state == last_state:
            slice_length += 1
        else:
            if 0 < slice_length <= 3:
                base = alphabet.get(last_state, "")
                isolated_candidates.append({
                    'base': base,
                    'start_t': slice_start,
                    'end_t': t,
                    'raw_start': output_to_abs_in_idx(slice_start),
                    'raw_end': output_to_abs_in_idx(t)
                })
            
            slice_start = t
            slice_length = 1
        last_state = current_state

    scales = [0.1, 0.2, 0.3, 0.4] 
    
    for cand in isolated_candidates:
        start_idx = cand['raw_start']
        end_idx = cand['raw_end']
        
        if start_idx < 0 or end_idx >= 4000:
            continue
            
        for scale in scales:
            corrupted_input = clean_input.clone()
            
            # FIX 2: Correctly slice the 3D tensor [batch=0, channel=0, sequence_start:sequence_end]
            corrupted_input[0, 0, start_idx:end_idx] = corrupted_input[0, 0, start_idx:end_idx] * scale
            
            with model.trace(corrupted_input):
                corrupted_output_proxy = model.output.save()
                
            corrupt_str = bonito_model.decode(corrupted_output_proxy.detach()[:, 0, :])
            
            is_valid, hbegin_idx, base_l = is_single_isolated_deletion(clean_str, corrupt_str)

            if is_valid:
                print(f"Success! Negative Control deletion of {base_l} at string idx {hbegin_idx}")
                
                records.append({
                    'base': f"['{base_l}']",
                    'num_bases': '[1]',
                    'duration_viterbi': cand['end_t'] - cand['start_t'],
                    'raw start idx': chunk_start + start_idx, 
                    'raw end idx': chunk_start + end_idx,
                    'input_base_timestamps': f"[{chunk_start + start_idx}]",
                    'Dampen width': 1.0,
                    'Scale Factor': scale,
                    'Clean string': clean_str,
                    'Corrupt_string': corrupt_str,
                    'H Begin Idx': hbegin_idx, 
                    'Base Letter': base_l,
                    'Clean H-er Length': 1, 
                    'Corrupt H-er Length': 0,
                    'Type': "Deletion",
                    'Corruption Start Raw': chunk_start + start_idx,
                    'Corruption End Raw': chunk_start + end_idx,
                    'Noise source idx': "Negative_Control",
                    'Insert idx': "N/A"
                })
                break 

    del clean_output_proxy

df = pd.DataFrame(records)

if not df.empty:
    df.to_csv(f'Negative_Control_results_read_{NUM_READ}.csv', index=False)
    print(f"saved results!")
else:
    print(f"nothing found")