############# THIS SCRIPT WAS GENERATED BY GEMINI #############

import torch
import os
import difflib
import pandas as pd
import numpy as np
from bonito import util
from bonito.reader import Reader, read_chunks
from nnsight import NNsight

##############################
######## MODEL SETUP #########
##############################

torch._dynamo.disable() 
import warnings
warnings.filterwarnings("ignore", category=UserWarning, module="torch.nn.attention.flex_attention")

model_path = "dna_r10.4.1_e8.2_400bps_sup@v5.2.0"
bonito_model = util.load_model(model_path, device="cuda" if torch.cuda.is_available() else "cpu")
model = NNsight(bonito_model._orig_mod)
model_dtype = next(model.parameters()).dtype # Gets the float16 type

##############################
######## FUNCTIONS ###########
##############################

def output_to_abs_in_idx(idx):
    return (idx * 6) - 14

def get_homopolymer_len(string, idx):
    ''' Get the number of repeating characters at the given idx '''
    if not string or idx < 0 or idx >= len(string):
        return 0, 0, 0
        
    begin = end = idx
    char = string[idx]
    length = 1

    while (begin > 0 and string[begin - 1] == char):
        length = length + 1
        begin = begin - 1
    
    while (end < len(string) - 1) and string[end + 1] == char:
        length = length + 1
        end = end + 1

    return (length, begin, end)

# def is_strictly_one_indel_in_chopped_slice(str1, str2, target_base=None):
#     """
#     Compares two decoded strings.
#     Returns True ONLY if there is exactly 1 isolated deletion OR 1 isolated insertion,
#     and ensures that neither the deleted nor inserted base is part of a homopolymer.
#     """
#     matcher = difflib.SequenceMatcher(None, str1, str2)
#     opcodes = matcher.get_opcodes()
    
#     error_count = 0
#     error_base = ""
#     target_idx = -1
#     error_type = ""
#     str2_insert_idx = -1
    
#     for tag, i1, i2, j1, j2 in opcodes:
#         if tag == 'equal':
#             continue
#         elif tag == 'delete':
#             # Check if it's exactly a 1-base deletion
#             if (i2 - i1) == 1:
#                 error_count += 1
#                 target_idx = i1
#                 error_base = str1[i1]
#                 error_type = "delete"
#             else:
#                 return False, 0, "" 
#         elif tag == 'insert':
#             # Check if it's exactly a 1-base insertion
#             if (j2 - j1) == 1:
#                 error_count += 1
#                 target_idx = i1 # We log the index relative to the clean string
#                 str2_insert_idx = j1 # We track the corrupt string index for the homopolymer check
#                 error_base = str2[j1]
#                 error_type = "insert"
#             else:
#                 return False, 0, ""
#         else:
#             # We found a 'replace' or complex error
#             return False, 0, "" 
            
#     # If we found exactly one 1-base error, verify homopolymer rules
#     if error_count == 1:
        
#         if error_type == "delete":
#             # For deletions, check the clean string
#             hlen, _, _ = get_homopolymer_len(str1, target_idx)
#         elif error_type == "insert":
#             # For insertions, check the corrupt string!
#             hlen, _, _ = get_homopolymer_len(str2, str2_insert_idx)
        
#         # Must be length 1 (an isolated base)
#         if hlen == 1:
#             if target_base is None or error_base == target_base:
#                 return True, target_idx, error_base
                
#     return False, 0, ""

def is_strictly_one_replacement_in_chopped_slice(str1, str2, target_base=None):
    """
    Returns True ONLY if there is exactly 1 isolated base substitution (e.g., A -> G).
    Ensures that neither the original base nor the new base creates a homopolymer.
    """
    matcher = difflib.SequenceMatcher(None, str1, str2)
    opcodes = matcher.get_opcodes()
    
    error_count = 0
    clean_base = ""
    corrupt_base = ""
    target_idx = -1
    
    for tag, i1, i2, j1, j2 in opcodes:
        if tag == 'equal':
            continue
        elif tag == 'replace':
            # Check if exactly 1 base was replaced by exactly 1 base
            if (i2 - i1) == 1 and (j2 - j1) == 1:
                error_count += 1
                target_idx = i1
                clean_base = str1[i1]
                corrupt_base = str2[j1]
            else:
                return False, 0, "", ""
        else:
            # Reject if there are any insertions or deletions anywhere
            return False, 0, "", "" 
            
    # If we found exactly one 1-base replacement, verify homopolymer rules
    if error_count == 1:
        
        # Check the clean string to ensure it's an isolated base
        hlen1, _, _ = get_homopolymer_len(str1, target_idx)
        # Check the corrupt string to ensure the NEW letter didn't accidentally form a homopolymer
        hlen2, _, _ = get_homopolymer_len(str2, target_idx)
        
        # BOTH must be length 1 (isolated bases)
        if hlen1 == 1 and hlen2 == 1:
            if target_base is None or clean_base == target_base:
                # Return both bases so you can log the mutation (e.g., A -> G)
                return True, target_idx, clean_base, corrupt_base
                
    return False, 0, "", ""

##############################
######## MAIN LOOP ###########
##############################

data_dir = "../data/reads/" # Update this
reader = Reader(data_dir)
reads = reader.get_reads(
    data_dir, 
    do_trim=True,
    scaling_strategy=model.config.get("scaling"),
    norm_params=model.config.get("standardisation")
)

NUM_READ = 7
for i in range(1, NUM_READ):
    next(reads)
first_read = next(reads)

records = []
alphabet = {1: "A", 2: "C", 3: "G", 4: "T"}

print(f"--- Generating Negative Controls for Read {NUM_READ} ---")

# 1. Grab the raw signal exactly like you do in Test_Inputs_new.py
raw_stndrd_signal = first_read.signal

chunksize = 4000
overlap = 400
step_size = chunksize - overlap

for chunk_idx, chunk_start in enumerate(range(0, len(raw_stndrd_signal) - chunksize + 1, step_size)):
    if chunk_idx >= 5: 
        break
        
    chunk_end = chunk_start + chunksize
    chunk = raw_stndrd_signal[chunk_start:chunk_end].copy()
    
    device = "cuda" if torch.cuda.is_available() else "cpu"
    # FIX 1: Use model_dtype instead of torch.float32
    clean_input = torch.tensor(chunk, dtype=model_dtype).view(1, 1, chunksize).to(device)
    
    with model.trace(clean_input):
        clean_output_proxy = model.output.save()
        
    clean_logits = clean_output_proxy.detach()
    clean_str = bonito_model.decode(clean_logits[:, 0, :])
    
    # Use the exact same Viterbi extraction from find_kmers.py
    viterbi_tensor = bonito_model._orig_mod.seqdist.viterbi(clean_logits.to(dtype=torch.float32))
    
    # Flatten it into a standard Python list
    viterbi_path = viterbi_tensor.flatten().tolist()
    
    # Append -1 to match your original find_kmers logic
    viterbi_path.append(-1)


    isolated_candidates = []
    last_state = -1
    slice_start = 0
    slice_length = 0
    
    for t in range(len(viterbi_path)):
        current_state = viterbi_path[t]
        if current_state == 0: 
            continue
            
        if current_state == last_state:
            slice_length += 1
        else:
            if 0 < slice_length <= 3:
                base = alphabet.get(last_state, "")
                isolated_candidates.append({
                    'base': base,
                    'start_t': slice_start,
                    'end_t': t,
                    'raw_start': output_to_abs_in_idx(slice_start),
                    'raw_end': output_to_abs_in_idx(t)
                })
            
            slice_start = t
            slice_length = 1
        last_state = current_state

    scales = [0.1, 0.2, 0.3, 0.4] 
    
    for cand in isolated_candidates:
        start_idx = cand['raw_start']
        end_idx = cand['raw_end']
        
        if start_idx < 0 or end_idx >= 4000:
            continue
            
        for scale in scales:
            
            # 1. APPLY NOISE FIRST (Create corrupted_input)
            corrupted_chunk = chunk.copy()
            hetero_len = end_idx - start_idx
            dampen_radius = max(1, int((hetero_len / 2) * 1.0)) 
            midpoint = (start_idx + end_idx) // 2
            local_mean = np.mean(corrupted_chunk[midpoint - dampen_radius : midpoint + dampen_radius])
            
            corrupted_chunk[midpoint - dampen_radius : midpoint + dampen_radius] = ( 
                (corrupted_chunk[midpoint - dampen_radius : midpoint + dampen_radius] * scale) 
                + (local_mean * (1-scale))
            )
            corrupted_input = torch.tensor(corrupted_chunk, dtype=model_dtype).view(1, 1, chunksize).to(device)

            # 2. MATCH RUN_PATCHES.PY CHOPPING LOGIC EXACTLY
            abs_start = chunk_start + start_idx
            abs_end = chunk_start + end_idx
            
            CONTEXT_PADDING = 200
            # We calculate boundaries relative to the 4000-tick chunk
            slice_start = max(0, start_idx - CONTEXT_PADDING)
            slice_end = min(chunksize, end_idx + CONTEXT_PADDING)
            
            # 3. CHOP
            chopped_clean_input = clean_input[:, :, slice_start:slice_end]
            chopped_corrupt_input = corrupted_input[:, :, slice_start:slice_end]
            
            # 4. DECODE CLEAN CHOPPED SLICE
            with model.trace(chopped_clean_input):
                chopped_clean_proxy = model.output.save()
            chopped_clean_str = bonito_model.decode(chopped_clean_proxy.detach()[:, 0, :])
            
            # 5. DECODE CORRUPT CHOPPED SLICE
            with model.trace(chopped_corrupt_input):
                chopped_corrupt_proxy = model.output.save()
            chopped_corrupt_str = bonito_model.decode(chopped_corrupt_proxy.detach()[:, 0, :])
            
            # 6. COMPARE
            is_valid, hbegin_idx, clean_l, corrupt_l = is_strictly_one_replacement_in_chopped_slice(
                chopped_clean_str, 
                chopped_corrupt_str, 
                target_base=cand['base']
            )

            if is_valid:
                print(f"Success! Negative Control Substitution: {clean_l} mutated to {corrupt_l} at string idx {hbegin_idx}")
                
                # Update your records dictionary:
                # 'Base Letter': f"{clean_l}->{corrupt_l}",
                # 'Type': "Negative_Control_Substitution",

                records.append({
                    # 'base': f"['{base_l}']",
                    'clean base': clean_l,
                    'corrupt base': corrupt_l,
                    'num_bases': '[1]',
                    'duration_viterbi': cand['end_t'] - cand['start_t'],
                    'raw start idx': abs_start, 
                    'raw end idx': abs_end,
                    'input_base_timestamps': f"[{abs_start}]",
                    'Dampen width': 1.0,
                    'Scale Factor': scale,
                    'Clean string': chopped_clean_str,       # Fixed to use chopped string
                    'Corrupt_string': chopped_corrupt_str,   # Fixed to use chopped string
                    'H Begin Idx': hbegin_idx, 
                    # 'Base Letter': base_l,
                    'Clean H-er Length': 1, 
                    'Corrupt H-er Length': 0,
                    'Type': "Negative_Control",
                    'Corruption Start Raw': abs_start,
                    'Corruption End Raw': abs_end,
                    'Noise source idx': None,
                    'Insert idx': None
                })
                break

    del clean_output_proxy

df = pd.DataFrame(records)

if not df.empty:
    df.to_csv(f'Negative_Control_results_read_{NUM_READ}.csv', index=False)
    print(f"saved results!")
else:
    print(f"nothing found")