########### THIS SCRIPT WAS GENERATED BY GEMINI ##########

import torch
import pandas as pd
import numpy as np
import json
import os
import difflib
from pathlib import Path
from bonito import util
from bonito.reader import Reader
from koi.decode import beam_search, to_str # Ensure to_str is available

# --- SETUP ---
model_path = "dna_r10.4.1_e8.2_400bps_sup@v5.2.0"
data_dir = "./data/reads/"
input_dir = Path("./data/pairs/")
output_lookup = "extended_moves_lookup.json"
device = "cuda" if torch.cuda.is_available() else "cpu"

CONTEXT_PADDING = 200 
NOISE_SIZE = 6

# Load Model
bonito_model = util.load_model(model_path, device=device)
model = bonito_model._orig_mod

# Helper to get the same signals as Run_Patches.txt
def get_signals(raw_signal, row):
    # Helper to handle the brackets in the CSV strings
    def clean_int(val):
        if isinstance(val, str):
            val = val.strip('[]')
        return int(float(val)) # Use float then int to handle cases like '8730.0'

    raw_start = clean_int(row['raw start idx'])
    raw_end = clean_int(row['raw end idx'])
    
    # Use your exact logic from Run_Patches.txt 
    chunk_start = max(0, raw_start - CONTEXT_PADDING)
    chunk_end = min(len(raw_signal), raw_end + CONTEXT_PADDING)
    clean_chunk = raw_signal[chunk_start:chunk_end].copy()
    
    corrupt_chunk = clean_chunk.copy()
    
    # Apply corruption (Dampen/Scale) 
    dampen_w = row.get('Dampen width')
    scale_f = row.get('Scale Factor')
    if not pd.isna(dampen_w) and not pd.isna(scale_f):
        # Calculate midpoint relative to the chunk 
        rel_start = raw_start - chunk_start
        rel_end = raw_end - chunk_start
        mid = (rel_start + rel_end) // 2
        h_len = rel_end - rel_start
        
        radius = max(1, int((h_len / 2) * dampen_w))
        local_mean = np.mean(corrupt_chunk[mid - radius : mid + radius])
        corrupt_chunk[mid - radius : mid + radius] = (
            (corrupt_chunk[mid - radius : mid + radius] * scale_f) + (local_mean * (1 - scale_f))
        )
    
    # Apply noise injection 
    n_idx = row.get('Noise source idx')
    i_idx = row.get('Insert idx')
    if not pd.isna(n_idx) and not pd.isna(i_idx):
        # Noise indices are often relative to the homopolymer or chunk in your data 
        n_start = int(clean_int(n_idx))
        i_start = int(clean_int(i_idx))
        corrupt_chunk[i_start : i_start + NOISE_SIZE] = corrupt_chunk[n_start : n_start + NOISE_SIZE]
        
    return clean_chunk, corrupt_chunk

def get_beam_results(signal_array):
    # Convert signal to the FP16 tensor format expected by the model
    tensor_in = torch.tensor(signal_array, dtype=torch.float16).view(1, 1, -1).to(device)
    
    with torch.no_grad():
        scores = model(tensor_in)
    
    # beam_search returns (sequence_, qstring_, moves_) 
    seq_tensor, qstring_tensor, moves_tensor = beam_search(scores.half())
    
    # Convert the sequence tensor IDs into a readable string 
    decoded_string = to_str(seq_tensor.cpu())
    
    return decoded_string, moves_tensor

# Process Reads
reader = Reader(data_dir)
reads = list(reader.get_reads(data_dir, do_trim=True))
extended_lookup = {}

for read_idx, read_data in enumerate(reads, start=1):
    csv_file = input_dir / f"Input_gen_results_read_{read_idx}.csv"
    if not csv_file.exists(): continue
    
    df_input = pd.read_csv(csv_file)
    for row_idx, row in df_input.iterrows():
        clean_sig, corrupt_sig = get_signals(read_data.signal, row)
        
        # Get Beam Search versions
        beam_clean_str, clean_moves = get_beam_results(clean_sig)
        beam_corrupt_str, _ = get_beam_results(corrupt_sig)
        
        # Get Original (Experiment) versions from CSV
        orig_clean_str = row['Clean string']
        orig_corrupt_str = row['Corrupt_string']
        
        # Map moves to base indices
        base_map = torch.cumsum(clean_moves, dim=0).cpu().numpy().tolist()
        
        # Store everything
        extended_lookup[f"R{read_idx}_r{row_idx}"] = {
            "orig_clean": orig_clean_str,
            "beam_clean": beam_clean_str,
            "orig_corrupt": orig_corrupt_str,
            "beam_corrupt": beam_corrupt_str,
            "base_map": base_map,
            # Quick check: did Beam Search "fix" the corruption?
            "is_fixed_by_beam": beam_clean_str == beam_corrupt_str,
            "clean_mismatch": beam_clean_str != orig_clean_str
        }

with open(output_lookup, 'w') as f:
    json.dump(extended_lookup, f, indent=4)